---
# vim: set filetype=yaml expandtab tabstop=2 shiftwidth=2 softtabstop=2 background=dark :
# handlers file for postgresql-ha

- name: restart postgresql
  service: name="{{ postgres_ha_pg_systemd_svcname }}" state=restarted

- name: reload postgresql
  shell: "{{ postgres_ha_pg_bindir }}/pg_ctl -D {{ postgres_ha_pg_data }} reload"
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: no

- name: reload corosync
  shell: pcs cluster reload corosync

- name: restart corosync
  service: name=corosync state=restarted

- name: reload systemd
  shell: /bin/systemctl daemon-reload

